- name: Check Ruby version
  shell: /usr/bin/ruby -e 'print RUBY_VERSION'
  ignore_errors: true
  register: ruby_version

- name: Install Ruby
  yum: name={{ item }} state=present
  with_items:
    - libyaml
    - "https://github.com/feedforce/ruby-rpm/releases/download/2.2.1/ruby-2.2.1-1.el7.centos.x86_64.rpm"
  when: ruby_version.stdout != "2.2.1"

- name: Install Bundler
  gem: name=bundler state=present user_install=no