- hosts: all
  sudo: yes
  tasks:
    - name: Update all packages
      yum: name='*' state=latest
    - name: Install dependencies for ruby-build
      yum: name={{ item }} state=present
      with_items:
        - autoconf
        - bison
        - openssl-devel
        - libyaml-devel
        - zlib-devel
        - readline-devel
        - gcc-c++
        - patch
        - automake
        - libtool
        - libffi-devel
    - name: Download Ruby source
      get_url: url=http://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.1.tar.gz dest=/root/ruby-2.2.1.tar.gz sha256sum=5a4de38068eca8919cb087d338c0c2e3d72c9382c804fb27ab746e6c7819ab28
      register: get_url_result

    - name: Extract Ruby source
      shell: tar -zxf /root/ruby-2.2.1.tar.gz chdir=/root
      when: get_url_result|success

    - name: Configure Ruby 2.2.1
      shell: ./configure chdir=/root/ruby-2.2.1
      when: get_url_result|success

    - name: Install Ruby 2.2.1
      shell: make install chdir=/root/ruby-2.2.1
      when: get_url_result|success
