---
- hosts: all
  vars_files:
    - vars/defaults.yml
    - vars/secrets.yml

  roles:
    # - webserver
    - {role: ruby, sudo: yes}
    - {role: database, sudo: yes}

  handlers:
    - name: Restart PostgreSQL
      sudo: true
      service: name=postgresql state=restarted