---
- hosts: all
  roles:
    - {role: ruby, sudo: yes}
    - {role: database, sudo: yes}
    - {role: apache, sudo: yes}
    - {role: passenger, sudo: yes}
    # - {role: ec2, sudo: yes}
    - {role: ssh, sudo: yes}

  handlers:
    - name: Restart PostgreSQL
      sudo: true
      service: name=postgresql state=restarted
    - name: Restart Apache
      sudo: true
      service: name=httpd state=restarted

  vars_files:
    - vars/defaults.yml
    - vars/secrets.yml